#ifndef WIDGET_H
#define WIDGET_H

#include <QWidget>

namespace Ui {
class widget;
}

/**
 * \class widget
 * \brief Minimal host window generated by Qt Designer.
 */
class widget : public QWidget
{
    Q_OBJECT

public:
    /**
     * \brief Construct the host window.
     * \param parent Optional parent widget.
     */
    explicit widget(QWidget *parent = nullptr);
    /**
     * \brief Destructor.
     */
    ~widget();

private:
    Ui::widget *ui;
};

#endif // WIDGET_H
